### ISSUE TITLE
build failed on win7 32 bit

### ISSUE THREAD

**Issue by redstoneleo** [brrd/Abricotine#206]
**console log**

```

C:\Users\i\Downloads\Abricotine-0.5.0>npm install

> spellchecker@3.4.4 install C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\
spellchecker
> node-gyp rebuild


C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\spellchecker>if not defined n
pm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-
bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebui
ld )
Warning: Missing input files:
C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\spellchecker\build\..\vendor\
hunspell\src\hunspell\utf_info.hxx
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  affentry.cxx
  affixmgr.cxx
  csutil.cxx
  dictmgr.cxx
  filemgr.cxx
  hashmgr.cxx
  hunspell.cxx
  hunzip.cxx
  phonet.cxx
  replist.cxx
  suggestmgr.cxx
  textparser.cxx
  win_delay_load_hook.cc
  hunspell.vcxproj -> C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\spellc
  hecker\build\Release\\hunspell.lib
  main.cc
  worker.cc
  spellchecker_hunspell.cc
  spellchecker_win.cc
  transcoder_win.cc
  win_delay_load_hook.cc
     Creating library C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\spellc
  hecker\build\Release\spellchecker.lib and object C:\Users\i\Downloads\Abricot
  ine-0.5.0\node_modules\spellchecker\build\Release\spellchecker.exp
  Generating code
  Finished generating code
  spellchecker.vcxproj -> C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\sp
  ellchecker\build\Release\\spellchecker.node
  spellchecker.vcxproj -> C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\sp
  ellchecker\build\Release\spellchecker.pdb (Full PDB)

> Abricotine@0.5.0 postinstall C:\Users\i\Downloads\Abricotine-0.5.0
> electron-rebuild

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 23.23.247.89:443
gyp ERR! stack     at Object._errnoException (util.js:1021:11)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1043:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:1
4)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\i\\Downloads\
\Abricotine-0.5.0\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target
=1.7.9" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-fr
om-source"
gyp ERR! cwd C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\spellchecker
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 23.23.247.89:443
gyp ERR! stack     at Object._errnoException (util.js:1021:11)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1043:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:1
4)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\i\\Downloads\
\Abricotine-0.5.0\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target
=1.7.9" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-fr
om-source"
gyp ERR! cwd C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\spellchecker
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules
\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\i\Downloads\Abricotine-0.5.0\node_m
odules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\
rxjs\Subscriber.js:197:26)
    at Subscriber._error (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\rxj
s\Subscriber.js:128:26)
    at Subscriber.error (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\rxjs
\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (C:\Users\i\Downloads\Abricotine-0.5.0\no
de_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (C:\Users\i\Downloads\Abricotine-0.5.0\nod
e_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\
spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (C:\Users\i\Downloads\Abricotine-0.5.0\nod
e_modules\rxjs\Subscriber.js:247:16)
    at SafeSubscriber.next (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\r
xjs\Subscriber.js:187:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! Abricotine@0.5.0 postinstall: `electron-rebuild`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the Abricotine@0.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\i\AppData\Roaming\npm-cache\_logs\2017-10-21T09_09_55_433Z
-debug.log

C:\Users\i\Downloads\Abricotine-0.5.0>npm install

> Abricotine@0.5.0 postinstall C:\Users\i\Downloads\Abricotine-0.5.0
> electron-rebuild

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 52.216.20.227:443
gyp ERR! stack     at Object._errnoException (util.js:1021:11)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1043:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:1
4)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\i\\Downloads\
\Abricotine-0.5.0\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target
=1.7.9" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-fr
om-source"
gyp ERR! cwd C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\spellchecker
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 52.216.20.227:443
gyp ERR! stack     at Object._errnoException (util.js:1021:11)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1043:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:1
4)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\i\\Downloads\
\Abricotine-0.5.0\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target
=1.7.9" "--arch=ia32" "--dist-url=https://atom.io/download/electron" "--build-fr
om-source"
gyp ERR! cwd C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\spellchecker
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules
\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\i\Downloads\Abricotine-0.5.0\node_m
odules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\
rxjs\Subscriber.js:197:26)
    at Subscriber._error (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\rxj
s\Subscriber.js:128:26)
    at Subscriber.error (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\rxjs
\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (C:\Users\i\Downloads\Abricotine-0.5.0\no
de_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (C:\Users\i\Downloads\Abricotine-0.5.0\nod
e_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\
spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (C:\Users\i\Downloads\Abricotine-0.5.0\node_m
odules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (C:\Users\i\Downloads\Abricotine-0.5.0\node_modules\r
xjs\Subscriber.js:185:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! Abricotine@0.5.0 postinstall: `electron-rebuild`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the Abricotine@0.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\i\AppData\Roaming\npm-cache\_logs\2017-10-21T09_19_46_860Z
-debug.log

C:\Users\i\Downloads\Abricotine-0.5.0>
```

**Comment by brrd** [comment]
Did you install node-gyp dependencies?
https://github.com/nodejs/node-gyp#installation

**Comment by redstoneleo** [comment]
Yes, already installed the following
```
npm install -g node-gyp
npm install --global --production windows-build-tools
```

**Comment by brrd** [comment]
This should be fixed on the develop branch.
