### ISSUE TITLE
Crash on close

### ISSUE THREAD

**Issue by fimdomeio** [brrd/Abricotine#256]
Hello Just downloaded Abricotine yesterday. On close I got this message:

Uncaught Exception:
AssertionError [ERR_ASSERTION]: rimraf: callback function required
    at rimraf (/Applications/Abricotine.app/Contents/Resources/app.asar/node_modules/rimraf/rimraf.js:51:10)
    at Object.rm (/Applications/Abricotine.app/Contents/Resources/app.asar/app/files.js:123:9)
    at AbrApplication.emptyTmpHTML (/Applications/Abricotine.app/Contents/Resources/app.asar/app/abr-application.js:146:15)
    at App.<anonymous> (/Applications/Abricotine.app/Contents/Resources/app.asar/app/index.js:51:12)
    at App.emit (events.js:187:15)

Thank you for this piece of software. I see it becoming very handy.

**Comment by brrd** [comment]
Good catch! 
`files.rm()` should provide a default callback such as:

```javascript
callback = callback || console.error;
```
