### ISSUE TITLE
About screen broken

### ISSUE THREAD

**Issue by nloveladyallen** [brrd/Abricotine#96]
With a window open Abricotine>About Abricotine does nothing. Without a window open, it gives this error:

> A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'createFromPath' of undefined
    at Object.about (/Users/noah/src/Abricotine/dist/Abricotine-darwin-x64/Abricotine.app/Contents/Resources/app.asar/app/dialogs.js:30:32)
    at Object.about (/Users/noah/src/Abricotine/dist/Abricotine-darwin-x64/Abricotine.app/Contents/Resources/app.asar/app/commands-main.js:41:17)
    at Object.execCommand (/Users/noah/src/Abricotine/dist/Abricotine-darwin-x64/Abricotine.app/Contents/Resources/app.asar/app/abr-application.js:126:30)
    at /Users/noah/src/Abricotine/dist/Abricotine-darwin-x64/Abricotine.app/Contents/Resources/app.asar/app/abr-menu.js:33:42
    at MenuItem.click (/Users/noah/src/Abricotine/dist/Abricotine-darwin-x64/Abricotine.app/Contents/Resources/electron.asar/browser/api/menu-item.js:59:9)
    at Function.executeCommand (/Users/noah/src/Abricotine/dist/Abricotine-darwin-x64/Abricotine.app/Contents/Resources/electron.asar/browser/api/menu.js:119:40)

**Comment by brrd** [comment]
I guess it's on OSX. Which version of Abricotine are you using?

**Comment by nloveladyallen** [comment]
Built from develop.

**Comment by nloveladyallen** [comment]
The issue was introduced with the Electron upgrade, FWIW. Worked fine as of b41c05e (commit before Electron upgrade) and broken as of e91f99a (upgrade) through 7184ea7 (latest commit).
